# Generated by Django 5.1.5 on 2025-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_doctor_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/', verbose_name='Patient Photo'),
        ),
    ]
